//
//  HomeModels.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 16/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  
    // MARK: Use cases
    enum Posts {
        struct Request {
            let isRefresh: Bool
            let limit: Int
            let query: String?
        }
        struct Response {
            let news: [New.Child]
        }
        struct ViewModel {
            let posts: [New.Child]
        }
    }
}
