//
//  HomeRouter.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 16/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToAuthorizationCarousel()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
  
    // MARK: - Routing
    func routeToAuthorizationCarousel() {
        let destinationVC = AuthorizationCarouselViewController()
        navigateToAuthorizationCarousel(source: viewController!, destination: destinationVC)
    }

    // MARK: - Navigation
    func navigateToAuthorizationCarousel(source: HomeViewController, destination: AuthorizationCarouselViewController) {
        source.view.window?.setRootViewController(destination)
    }
}
