//
//  HomeWorker.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 16/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol NewServiceProtocol {
    func fetchNews(request: New.FecthNews.Request,
                   completion: @escaping (Result<New.FecthNews.Response, ErrorReddit>) -> Void)
    func searchNews(request: New.SearchNews.Request,
                    completion: @escaping (Result<New.SearchNews.Response, ErrorReddit>) -> Void)
}

class HomeWorker {
    var newService: NewServiceProtocol?
    
    init(newService: NewServiceProtocol) {
        self.newService = newService
    }
    
    func fetchNews(request: New.FecthNews.Request,
                   completion: @escaping (Result<New.FecthNews.Response, ErrorReddit>) -> Void) {
        newService?.fetchNews(request: request, completion: { result in
            completion(result)
        })
    }
    
    func searchNews(request: New.SearchNews.Request,
                    completion: @escaping (Result<New.SearchNews.Response, ErrorReddit>) -> Void) {
        newService?.searchNews(request: request, completion: { result in
            completion(result)
        })
    }
}
