//
//  AuthorizationCarouselViewController.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 15/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationCarouselDisplayLogic: class {
    func displaySomething(viewModel: AuthorizationCarousel.Something.ViewModel)
}

class AuthorizationCarouselViewController: UIViewController {
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    var interactor: AuthorizationCarouselBusinessLogic?
    var router: (NSObjectProtocol & AuthorizationCarouselRoutingLogic & AuthorizationCarouselDataPassing)?

    // MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: - Setup
    private func setup() {
        let viewController = self
        let interactor = AuthorizationCarouselInteractor()
        let presenter = AuthorizationCarouselPresenter()
        let router = AuthorizationCarouselRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doSomething()
    }

    // MARK: - Do something
    func doSomething() {
        let request = AuthorizationCarousel.Something.Request()
        interactor?.doSomething(request: request)
    }
}

// MARK: - AuthorizationCarouselDisplayLogic
extension AuthorizationCarouselViewController: AuthorizationCarouselDisplayLogic {
    func displaySomething(viewModel: AuthorizationCarousel.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
