//
//  AuthorizationCarouselInteractor.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 15/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationCarouselBusinessLogic {
    func doSomething(request: AuthorizationCarousel.Something.Request)
}

protocol AuthorizationCarouselDataStore {
    //var name: String { get set }
}

class AuthorizationCarouselInteractor: AuthorizationCarouselBusinessLogic, AuthorizationCarouselDataStore {
    var presenter: AuthorizationCarouselPresentationLogic?
    var worker: AuthorizationCarouselWorker?
    //var name: String = ""
  
    // MARK: Do something
    func doSomething(request: AuthorizationCarousel.Something.Request) {
        worker = AuthorizationCarouselWorker()
        worker?.doSomeWork()
    
        let response = AuthorizationCarousel.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
