//
//  AuthorizationCarouselInteractor.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 15/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationCarouselBusinessLogic {
    func loadInitialData(request: AuthorizationCarousel.InitialData.Request)
}

protocol AuthorizationCarouselDataStore {}

class AuthorizationCarouselInteractor: AuthorizationCarouselBusinessLogic, AuthorizationCarouselDataStore {
    var presenter: AuthorizationCarouselPresentationLogic?
    var worker: AuthorizationCarouselWorker?
    
    // MARK: - loadInitialData
    func loadInitialData(request: AuthorizationCarousel.InitialData.Request) {
        let response = AuthorizationCarousel.InitialData.Response(items: AuthorizationCarousel.Item.allCases)
        presenter?.presentInitialData(response: response)
    }
}
