//
//  AuthorizationCarouselRouter.swift
//  Reddit Chile Memes
//
//  Created by Freddy Silva on 15/5/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthorizationCarouselRoutingLogic {
    func routeToHome()
}

protocol AuthorizationCarouselDataPassing {
    var dataStore: AuthorizationCarouselDataStore? { get }
}

class AuthorizationCarouselRouter: NSObject, AuthorizationCarouselRoutingLogic, AuthorizationCarouselDataPassing {
    weak var viewController: AuthorizationCarouselViewController?
    var dataStore: AuthorizationCarouselDataStore?
  
    // MARK: - Routing
    func routeToHome() {
        let destinationVC = HomeViewController()
        navigateToHome(source: viewController!, destination: destinationVC)
    }

    // MARK: - Navigation
    func navigateToHome(source: AuthorizationCarouselViewController, destination: HomeViewController) {
        source.view.window?.setRootViewController(destination)
    }
}
